@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

' Base Command and Parser interface
Class "{abstract}\nCommand" as Command
Class "<<interface>>\nParser" as Parser
Class ParserUtil
Class CliSyntax
Class Prefix
Class ArgumentTokenizer
Class ArgumentMultimap

' Core Parsers
Class AddressBookParser
Class AddCommandParser
Class DeleteCommandParser
Class DeleteTaskCommandParser
Class EditCommandParser
Class FindCommandParser
Class ListMemberTasksCommandParser
Class ReportCommandParser
Class SetDueDateCommandParser
Class TaskCommandParser
Class UpdateTaskCommandParser
Class RemarkCommandParser

' Predicates
Class NameContainsKeywordsPredicate
Class TagsInKeywordsPredicate
Class TasksInKeywordsPredicate

' Inheritance
AddCommandParser .up.|> Parser
DeleteCommandParser .up.|> Parser
DeleteTaskCommandParser .up.|> Parser
EditCommandParser .up.|> Parser
FindCommandParser .up.|> Parser
ListMemberTasksCommandParser .up.|> Parser
ReportCommandParser .up.|> Parser
SetDueDateCommandParser .up.|> Parser
TaskCommandParser .up.|> Parser
UpdateTaskCommandParser .up.|> Parser
RemarkCommandParser .up.|> Parser

' AddressBookParser parser creation
AddressBookParser --> AddCommandParser : <<create>>
AddressBookParser --> DeleteCommandParser
AddressBookParser --> DeleteTaskCommandParser
AddressBookParser --> EditCommandParser
AddressBookParser --> FindCommandParser
AddressBookParser --> ListMemberTasksCommandParser
AddressBookParser --> ReportCommandParser
AddressBookParser --> SetDueDateCommandParser
AddressBookParser --> TaskCommandParser
AddressBookParser --> UpdateTaskCommandParser
AddressBookParser --> RemarkCommandParser

' Common utilities used by most parsers
ParserUtil .down.> Prefix
ArgumentTokenizer .down.> Prefix
ArgumentTokenizer .left.> ArgumentMultimap
CliSyntax ..> Prefix
TaskCommandParser ..> ParserUtil
TaskCommandParser ..> ArgumentMultimap
TaskCommandParser ..> ArgumentTokenizer
TaskCommandParser ..> CliSyntax
RemarkCommandParser ..> ParserUtil

' Predicates for FindCommand
FindCommandParser ..> NameContainsKeywordsPredicate
FindCommandParser ..> TagsInKeywordsPredicate
FindCommandParser ..> TasksInKeywordsPredicate
FindCommandParser ..> ArgumentMultimap

@enduml
