@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

' Base command and example command
Class "{abstract}\nCommand" as Command
Class TaskCommand
TaskCommand -up-|> Command

' Parser package and core components
package "Parser classes" {

  Class "<<interface>>\nParser" as Parser
  Class AddressBookParser
  Class AddCommandParser
  Class DeleteCommandParser
  Class DeleteTaskCommandParser
  Class EditCommandParser
  Class FindCommandParser
  Class ListMemberTasksCommandParser
  Class ReportCommandParser
  Class SetDueDateCommandParser
  Class TaskCommandParser
  Class UpdateTaskCommandParser

  Class CliSyntax
  Class ParserUtil
  Class ArgumentMultimap
  Class ArgumentTokenizer
  Class Prefix

  Class NameContainsKeywordsPredicate
  Class TagsInKeywordsPredicate
  Class TasksInKeywordsPredicate
}

' Inheritance
AddCommandParser .up.|> Parser
DeleteCommandParser .up.|> Parser
DeleteTaskCommandParser .up.|> Parser
EditCommandParser .up.|> Parser
FindCommandParser .up.|> Parser
ListMemberTasksCommandParser .up.|> Parser
ReportCommandParser .up.|> Parser
SetDueDateCommandParser .up.|> Parser
TaskCommandParser .up.|> Parser
UpdateTaskCommandParser .up.|> Parser

' Parser creation relations
AddressBookParser .down.> AddCommandParser : <<create>>
AddressBookParser .down.> DeleteCommandParser : <<create>>
AddressBookParser .down.> DeleteTaskCommandParser : <<create>>
AddressBookParser .down.> EditCommandParser : <<create>>
AddressBookParser .down.> FindCommandParser : <<create>>
AddressBookParser .down.> ListMemberTasksCommandParser : <<create>>
AddressBookParser .down.> ReportCommandParser : <<create>>
AddressBookParser .down.> SetDueDateCommandParser : <<create>>
AddressBookParser .down.> TaskCommandParser : <<create>>
AddressBookParser .down.> UpdateTaskCommandParser : <<create>>

' FindCommandParser uses predicates
FindCommandParser ..> NameContainsKeywordsPredicate
FindCommandParser ..> TagsInKeywordsPredicate
FindCommandParser ..> TasksInKeywordsPredicate
FindCommandParser ..> ArgumentMultimap

' TaskCommandParser uses shared utilities
TaskCommandParser ..> ParserUtil
TaskCommandParser ..> ArgumentMultimap
TaskCommandParser ..> ArgumentTokenizer
TaskCommandParser ..> CliSyntax

' General dependencies
ParserUtil .down.> Prefix
ArgumentTokenizer .down.> Prefix
ArgumentTokenizer .left.> ArgumentMultimap
CliSyntax ..> Prefix

' External link
Class HiddenOutside #FFFFFF
HiddenOutside ..> AddressBookParser

@enduml
